### ISSUE TITLE
MSB5004 the solution file has two projects named "nodave"

### ISSUE THREAD

**Issue by sebascontre** [flosse/node-plc#1]
I got this error when I try to install `plc` with `npm`, and don't know how fix it u.u

![cmd](http://i.imgur.com/u8vvWlc.png)

**Comment by flosse** [comment]
Thanks for that feedback. I never tried to install it on windows :-\
Could you try to install it with node `v0.10.x`?

**Comment by flosse** [comment]
It seems to be a compatibility problem, it doesn't work with node `v0.12` yet :-\

**Comment by flosse** [comment]
@sebascontre would you mind to try it again with the current master?

**Comment by flosse** [comment]
this might be related to #2

**Comment by flosse** [comment]
I think this can be closed. Feel free to reopen if there are still problems.
