### ISSUE TITLE
Logo type

### ISSUE THREAD

**Issue by rofavadeka** [flosse/node-plc#3]
I came across your module and would love to give it a try.
Could you tell me which logo I require?

Thanks!

**Comment by flosse** [comment]
I tested it with a LOGO! 230RCE `0BA7`

**Comment by rofavadeka** [comment]
Thank's; also managed to get it working with the LOGO! 230RCE 0BA8 and LOGO! 24RCE 0BA8.
( version node v0.10.42 and npm 1.4.29 )
