### ISSUE TITLE
node-gyp configure build fails

### ISSUE THREAD

**Issue by rofavadeka** [flosse/node-plc#4]
Trying to get the PLC module working on a Raspberry Pi 3 running on Raspian Jessie Lite.
Unfortunately I can not install the package because node-gyp build fails.
Tried it also on my macbook to see if it was OS related but got the same issue.

Has anyone an idea how to solve this?

**Error Macbook:**

> `20 errors generated.
> make: *** [Release/obj.target/profiler/cpu_profiler.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error:`make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Darwin 15.3.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/rolf/Dev/plc/node_modules/v8-profiler
> gyp ERR! node -v v4.4.3
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok 
> npm ERR! Darwin 15.3.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "v8-profiler@3.6.2-1"
> npm ERR! node v4.4.3
> npm ERR! npm  v2.15.1
> npm ERR! code ELIFECYCLE
> 
> `npm ERR! v8-profiler@3.6.2-1 install:`node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the v8-profiler@3.6.2-1 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the v8-profiler package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs v8-profiler
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! 
> npm ERR!     npm owner ls v8-profiler
> npm ERR! There is likely additional logging output above.
> 
> `npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/rolf/Dev/plc/npm-debug.log
> `

**Comment by flosse** [comment]
I haven't used this module for a long time so it might be a problem with new node or npm versions. I tried to install it on node `v4.4.6` without success :(

**Comment by flosse** [comment]
FYI: It works with node v0.10.42 and npm 1.4.29

**Comment by rofavadeka** [comment]
Thanks for the quick response! Will give it a try with v0.10.42.
Would love to get this up and running with a current version of Node.

May I ask where you found documentation on the Siemens Logo webserver or how you figured out how to communicate with it; I couldn't find anything?

**Comment by flosse** [comment]
> Would love to get this up and running with a current version of Node.

me too ;-)

> May I ask where you found documentation on the Siemens Logo webserver

I didn't

> or how you figured out how to communicate with it; I couldn't find anything?

I used  LOGO!Soft Compfort to create the logic and configured the networking via the menu.

**Comment by flosse** [comment]
Hey guys,
[here](https://travis-ci.org/flosse/node-plc/builds/173132517) you can see how the builds fail with node `>0.12` so [I updated the code](https://github.com/flosse/node-plc/commit/0681533b8891955f2c5d210e1816420f4a24b70b) for `nan` to `2.4` and now it works on my local machine but on travis  [it is still failing](https://travis-ci.org/flosse/node-plc/builds/173133155).

Could you test the update on your local computer?

**Comment by flosse** [comment]
... adding g++ to the travis config [seems to fix the online builds](https://travis-ci.org/flosse/node-plc/builds/173134686) :)

**Comment by flosse** [comment]
As long as there are no responses I guess the problem is fixed :)
